version: '3.8'

networks:
  metrics_network:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  metrics:
    build: .
    container_name: metrics
    ports:
      - 9568:9568
      - 4021:4021
    expose:
      - 9568
      - 4021
    networks:
      - metrics_network

  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    expose:
      - 9090
    depends_on:
      - metrics
    networks:
      - metrics_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
    volumes:
      - ./config/grafana/data:/var/lib/grafana
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - prometheus
    networks:
      - metrics_network
