global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "telemetry_metrics_prometheus"
    static_configs:
    - targets: ["metrics:9568"]
